#!/usr/bin/env bash


delete_if_ln() {
    
    if [[ -L "$1" ]]; then
        rm $1
        echo "Removed symlink: $1"
    fi

}
delete_if_ln ~/.bash
ln -s ~/git/config/.bashrc ~/.bashrc

delete_if_ln ~/.tmux
ln -s ~/git/config/.tmux ~/.tmux

delete_if_ln ~/.tmux.conf
ln -s ~/git/config/.tmux.conf ~/.tmux.conf

delete_if_ln ~/.vimrc
ln -s ~/git/config/.vimrc ~/.vimrc

delete_if_ln ~/.config/polybar
ln -s ~/git/config/polybar ~/.config/polybar

delete_if_ln ~/.config/alacritty
ln -s ~/git/config/alacritty ~/.config/alacritty

delete_if_ln ~/.config/.alacritty.toml
ln -s ~/git/config/.alacritty.toml ~/.config/.alacritty.toml

delete_if_ln ~/.config/i3
ln -s ~/git/config/i3 ~/.config/i3
